#!/bin/sh
set -e
if [ -z "$D" ]; then
  echo "Starting virtual-gps services"
  cp -R /opt/victronenergy/service/virtual-gps-udp-redirect/ /service/
  cp -R /opt/victronenergy/service/virtual-gps-start/ /service/
fi
