#!/bin/sh
set -e
if [ -z "$D" ]; then
  echo "Stopping virtual-gps services"
  svc -d /service/virtual-gps-start
  svc -d /service/virtual-gps-udp-redirect
  sleep 1

  echo "Deleting virtual-gps services and logs"
  rm -R /service/virtual-gps-start
  rm -R /service/virtual-gps-udp-redirect
  rm -R /var/log/virtual-gps-start
  rm -R /var/log/virtual-gps-udp-redirect
fi
