#!/bin/sh
set -e
if [ -z "$D" ]; then
  # Copy service files for svscan to detect it within seconds and avoid a reboot
  cp -R /opt/victronenergy/service/virtual-gps-udp-redirect/ /service/
  cp -R /opt/victronenergy/service/virtual-gps-start/ /service/
fi
